       name: build and test 
       on:
          push:
               branches: [main,feature/**]
          workflow_dispatch:
       jobs:
          test_app:
               runs-on: ubuntu-latest
               steps:
                    - name: checkout repo
                      uses: actions/checkout@v5
                    - name: checkout message
                      run: |
                       echo 'checkout ${{github.ref}}'
                    - name: node js enviroment setup
                      uses: actions/setup-node@v5
                      with:
                         node-version: 20
                    - name: node version
                      run: node -v
                    - name: cahed dependencies
                      uses: actions/cache@v4
                      with:
                         path: '~/.npm'
                         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')  }}
                         restore-key: ${{runner.os}}-node
                         
                     
                    - name: dependencies installation
                      run: npm ci 
                    - name: test app 
                      run: npm test 

                        
                         